---
- name: coleta de informacoes ec2
  hosts: localhost
  gather_facts: False
  vars:
    ec2_region: us-east-1
  tasks:
  - name: retrive info for the EC2 instances
    amazon.aws.ec2_instance_info:
      region: "{{ ec2_region }}"
    register: ec2_instance_info

  - name: mostrar informacoes
    debug:
      var: ec2_instance_info

